foreach (required_variable IN ITEMS LIBRARY_FILE TEST_EXECUTABLE EXPECT_PROFILING BUILD_DIRECTORY)
    if (NOT DEFINED ${required_variable})
        message(FATAL_ERROR "${required_variable} is required")
    endif ()
endforeach ()

file(STRINGS "${LIBRARY_FILE}" PROFILING_MARKERS REGEX "HUXERUI_PROFILE_DIRECTORY")
if (EXPECT_PROFILING AND NOT PROFILING_MARKERS)
    message(FATAL_ERROR "HuxerUI profiling build does not contain its recorder")
elseif (NOT EXPECT_PROFILING AND PROFILING_MARKERS)
    message(FATAL_ERROR "HuxerUI non-profiling library contains performance diagnostic code")
endif ()

if (CROSSCOMPILING)
    return()
endif ()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef CAPTURE_NONCE)
foreach (mode IN ITEMS default empty directory_only overview detailed off off_directory invalid unavailable_directory)
    set(CAPTURE_WORK_DIRECTORY "${BUILD_DIRECTORY}/profiling-capture-${CAPTURE_NONCE}/${mode}")
    file(MAKE_DIRECTORY "${CAPTURE_WORK_DIRECTORY}")
    set(CAPTURE_DIRECTORY "${CAPTURE_WORK_DIRECTORY}/traces")
    set(CAPTURE_ENVIRONMENT --unset=HUXERUI_PROFILE --unset=HUXERUI_PROFILE_DIRECTORY)
    if (mode STREQUAL "directory_only" OR mode STREQUAL "detailed" OR mode STREQUAL "off_directory")
        set(CAPTURE_DIRECTORY "${CAPTURE_WORK_DIRECTORY}/custom traces")
        list(APPEND CAPTURE_ENVIRONMENT "HUXERUI_PROFILE_DIRECTORY=custom traces")
    endif ()
    set(EXPECT_CAPTURE ${EXPECT_PROFILING})
    if (mode STREQUAL "off" OR mode STREQUAL "off_directory")
        set(EXPECT_CAPTURE FALSE)
        list(APPEND CAPTURE_ENVIRONMENT "HUXERUI_PROFILE=off")
    elseif (mode STREQUAL "invalid")
        set(EXPECT_CAPTURE FALSE)
        list(APPEND CAPTURE_ENVIRONMENT "HUXERUI_PROFILE=invalid")
    elseif (mode STREQUAL "empty")
        list(APPEND CAPTURE_ENVIRONMENT "HUXERUI_PROFILE=")
    elseif (mode STREQUAL "overview" OR mode STREQUAL "detailed")
        list(APPEND CAPTURE_ENVIRONMENT "HUXERUI_PROFILE=${mode}")
    elseif (mode STREQUAL "unavailable_directory")
        set(EXPECT_CAPTURE FALSE)
        set(CAPTURE_DIRECTORY "${CAPTURE_WORK_DIRECTORY}/blocked/traces")
        file(WRITE "${CAPTURE_WORK_DIRECTORY}/blocked" "Not a directory.\n")
        list(APPEND CAPTURE_ENVIRONMENT "HUXERUI_PROFILE_DIRECTORY=blocked/traces")
    endif ()
    set(CAPTURE_FILTER "[.profiling-capture]")
    if (EXPECT_PROFILING AND mode STREQUAL "off")
        set(CAPTURE_FILTER "[.profiling-capture],[.profiling-runtime]")
    endif ()
    execute_process(
            COMMAND "${CMAKE_COMMAND}" -E env ${CAPTURE_ENVIRONMENT}
                    "${TEST_EXECUTABLE}" "${CAPTURE_FILTER}"
            WORKING_DIRECTORY "${CAPTURE_WORK_DIRECTORY}"
            RESULT_VARIABLE CAPTURE_RESULT
            OUTPUT_VARIABLE CAPTURE_OUTPUT
            ERROR_VARIABLE CAPTURE_ERROR
    )
    if (EXPECT_PROFILING AND mode STREQUAL "invalid")
        if (CAPTURE_RESULT EQUAL 0 OR NOT CAPTURE_OUTPUT MATCHES "HuxerUI profiling mode must be off, overview, or detailed")
            message(FATAL_ERROR "HuxerUI invalid profiling mode was not rejected:\n${CAPTURE_OUTPUT}${CAPTURE_ERROR}")
        endif ()
    elseif (NOT CAPTURE_RESULT EQUAL 0)
        message(FATAL_ERROR "HuxerUI profiling workload failed:\n${CAPTURE_OUTPUT}${CAPTURE_ERROR}")
    endif ()
    if (EXPECT_PROFILING AND mode STREQUAL "unavailable_directory" AND
            NOT CAPTURE_ERROR MATCHES "HuxerUI profiling could not prepare its output directory")
        message(FATAL_ERROR "HuxerUI profiling did not report its unavailable output directory")
    endif ()
    file(GLOB CAPTURE_FILES "${CAPTURE_DIRECTORY}/*.json")
    list(LENGTH CAPTURE_FILES CAPTURE_COUNT)
    if (NOT EXPECT_CAPTURE)
        if (EXISTS "${CAPTURE_DIRECTORY}" OR EXISTS "${CAPTURE_WORK_DIRECTORY}/traces")
            message(FATAL_ERROR "HuxerUI inactive profiling created a capture directory")
        endif ()
        continue()
    endif ()
    if (NOT CAPTURE_DIRECTORY STREQUAL "${CAPTURE_WORK_DIRECTORY}/traces" AND
            EXISTS "${CAPTURE_WORK_DIRECTORY}/traces")
        message(FATAL_ERROR "HuxerUI profiling ignored its output directory override")
    endif ()
    if (NOT CAPTURE_COUNT EQUAL 1)
        message(FATAL_ERROR "HuxerUI profiling workload did not export one Runtime trace: ${CAPTURE_FILES}")
    endif ()
    list(GET CAPTURE_FILES 0 CAPTURE_FILE)
    file(READ "${CAPTURE_FILE}" CAPTURE_JSON)
    string(JSON FRAME_COUNT GET "${CAPTURE_JSON}" huxerui frames)
    string(JSON TRUNCATED GET "${CAPTURE_JSON}" huxerui truncated)
    string(JSON SCOPE_COUNT GET "${CAPTURE_JSON}" huxerui counters scopes)
    string(JSON EVENT_COUNT LENGTH "${CAPTURE_JSON}" traceEvents)
    if (FRAME_COUNT LESS 2 OR SCOPE_COUNT LESS 1 OR EVENT_COUNT LESS 1 OR TRUNCATED)
        message(FATAL_ERROR "HuxerUI profiling export has invalid frame or counter data")
    endif ()
    if (CAPTURE_JSON MATCHES "application text must stay out of traces")
        message(FATAL_ERROR "HuxerUI profiling export contains application text")
    endif ()
    math(EXPR LAST_EVENT "${EVENT_COUNT} - 1")
    set(HAS_NODE_SPAN FALSE)
    foreach (index RANGE ${LAST_EVENT})
        string(JSON PHASE GET "${CAPTURE_JSON}" traceEvents ${index} ph)
        string(JSON DURATION GET "${CAPTURE_JSON}" traceEvents ${index} dur)
        string(JSON NAME GET "${CAPTURE_JSON}" traceEvents ${index} name)
        if (NOT PHASE STREQUAL "X" OR DURATION LESS 0)
            message(FATAL_ERROR "HuxerUI profiling export contains an invalid duration event")
        endif ()
        if (NAME STREQUAL "Scope")
            set(HAS_NODE_SPAN TRUE)
        endif ()
    endforeach ()
    if ((mode STREQUAL "overview" AND HAS_NODE_SPAN) OR (NOT mode STREQUAL "overview" AND NOT HAS_NODE_SPAN))
        message(FATAL_ERROR "HuxerUI profiling export did not respect its level")
    endif ()
endforeach ()

if (EXPECT_PROFILING AND SDK_INSTALL_AVAILABLE)
    execute_process(
            COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIRECTORY}" --config "${BUILD_CONFIG}"
                    --component HuxerUILibraries --prefix "${BUILD_DIRECTORY}/profiling-install-check"
            RESULT_VARIABLE INSTALL_RESULT
            OUTPUT_VARIABLE INSTALL_OUTPUT
            ERROR_VARIABLE INSTALL_ERROR
    )
    if (INSTALL_RESULT EQUAL 0 OR NOT INSTALL_ERROR MATCHES "HUXERUI_ENABLE_PROFILING=OFF")
        message(FATAL_ERROR "HuxerUI profiling SDK installation was not rejected:\n${INSTALL_OUTPUT}${INSTALL_ERROR}")
    endif ()
endif ()
